### PR TITLE
Friendships v2

### PR DESCRIPTION
**Pull request by RadiactiveJesus**
Implementing the mutual friendship feature

### CODE REVIEW

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

Hi Rodolfo! :wave: 

Nice work so far!

- However, interacting with your application, after sending a friend-request, the user that accepted the  request, is not automatically a friend to the user that sent the request. That is, when the user that accepts the friend-request signs into their account, they should have as a friend the user that requested for friendship
- Also, there should be a notification, when there is a friend request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

Implement these changes, then submit another form for a code review.


Reach-out if you need clarifications, on slack @ Inyama, Uchechukwu Henry

#### ``` Have a great day ``` :slightly_smiling_face: 


```Uchechukwu Henry Inyama ```

**Comment by RadiactiveJesus** [comment]
> ## Changes Required
> Hi Rodolfo! 👋
> 
> Nice work so far!
> 
> * However, interacting with your application, after sending a friend-request, the user that accepted the  request, is not automatically a friend to the user that sent the request. That is, when the user that accepts the friend-request signs into their account, they should have as a friend the user that requested for friendship
> * Also, there should be a notification, when there is a friend request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
> 
> Implement these changes, then submit another form for a code review.
> 
> Reach-out if you need clarifications, on slack @ Inyama, Uchechukwu Henry
> 
> #### `Have a great day` 🙂
> `Uchechukwu Henry Inyama `

Hello Uche, can you explain better how to create this mutual friendships now that you saw my project. I have been trying the last couple of days with no success, the information I have researched havent been much helpful. Thanks.
Also on the home page there is a link to friends there you can see all the notifications of received and sent friend requests

**Comment by samgaco** [comment]
Hi @RadiactiveJesus :high_brightness: 

You should have into account that when a friendship relation is created, of any status, another row should be also created in the database with the inverse relationship, building from that you can create this feature.

You are given this [artcile](https://explainextended.com/2009/03/07/selecting-friends/) and [stackoverflow](https://stackoverflow.com/questions/4219979/sql-best-practice-for-a-friendship-table) discussion as a hint.

If you have any trouble, you can book some 1 on 1 call with any of the full-time TSE's currently available. Their slack names;

- Bola Ahmed Buari
- James Okunlade
- Jorge Fernando Rincón Figueroa

Please, submit back once you are done with the changes suggested by @uche-inyama 

Good spirit :muscle: 

------------------------

* ###### STATUS OF THE PROJECT: REQUESTED CHANGES :stop_sign:

**Review by imhta — APPROVED** [review]
# Milestone approved 🎉 

### Hello  @RadiactiveJesus , 👋 You have done a great job in this milestone 👏 




----
### Happy coding 😄 
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__

**Pull request merged**
